version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - farm-network
    volumes:
      - ./backend:/app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"  # Ensure this matches the dev server port
    depends_on:
      - backend
    networks:
      - farm-network
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file watching
    command: pnpm run dev  # Start the dev server with HMR

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - farm-network

networks:
  farm-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local