services:
  app:
    build: .
    container_name: mse_app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mse_data
    volumes:
      - .:/app
    networks:
      - app-network

  mongo:
    image: mongo:8.0.3
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: